site_name: Welcome to OpenStreetMap
# site_url: https://welcome.openstreetmap.org/
site_url: https://andygol.co.ua/welcome-mat-osmf

# repo_url: https://github.com/osmfoundation/welcome-mat
# repo_name: osmfoundation/welcome-mat
repo_url: https://github.com/Andygol/welcome-mat-osmf
repo_name: Andygol/welcome-mat-osmf

edit_uri: edit/main/docs/

copyright: None

announce: 
  text: None
  toggle:
    - label: Show info
      icon: material/information-outline
    - label: Hide info 
      icon: material/information

extra_css:
  - stylesheets/extra.css
# Start of MkDocs theme adjastments

theme: 
  name: material
  custom_dir: overrides

  # logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    logo: simple/openstreetmap
    annotation: material/information-outline

  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: osml
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - toc.follow

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://openstreetmap.org/
    - icon: simple/openstreetmap
      link: https://osmfoundation.org/
    - icon: fontawesome/brands/github
      link: https://github.com/openstreetmap
    - icon: fontawesome/brands/discourse
      link: https://community.openstreetmap.org/
    - icon: simple/mastodon
      link: https://en.osm.town/@openstreetmap
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/openstreetmap 
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OpenStreetMap/  
    
# End of MkDocs theme adjastments

markdown_extensions:

  - admonition
  - attr_list # {:target="_blank"} opens links in a new tab
  - md_in_html

  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg   

  - toc:
      permalink: "#"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: none

# Navigation menu
nav:
  - Home: index.md
  # - About: about.md
  - What is OpenStreetMap: what-is-openstreetmap.md
  - Who is OpenStreetMap: who-is-openstreetmap.md
  - Why use OpenStreetMap: why-openstreetmap.md
  - How can we give back: how-to-give-back.md
  - About Community: 
    - History of OSM: about-osm-community/history-of-osm.md
    - OSMF: about-osm-community/osm-foundation.md
    - Local Chapters: about-osm-community/local-chapters.md
    - Working Groups: about-osm-community/working-groups.md
    - Consumers: about-osm-community/consumers.md
    - OSM News: about-osm-community/osm-news.md
    - Donate: about-osm-community/donate-to-osm.md
    - Contact: about-osm-community/get-in-touch.md
  - Working with data:
    - Data quality: working-with-osm-data/how-good-is-osm.md
    - Contribute data: working-with-osm-data/contribute-osm-data.md
    - Humanitarian campaign: working-with-osm-data/humanitarian-campaign.md
    - Research with OSM: working-with-osm-data/research-with-osm.md
    - Find a developer: working-with-osm-data/find-a-developer.md
    - Downloading and using: working-with-osm-data/downloading-and-using.md

plugins:
  - search:
      lang:
        - en
        - uk
  - macros
  - ezlinks
  - social:
      enabled: true
      cards_layout_options:
        background_color: "#7EBC6F"

# This part is for organising languages in specific folders
# Using a folder per language structure
# https://pypi.org/project/mkdocs-static-i18n/
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
          site_name: Welcome to OpenStreetMap
          announce:
            toggle:
              - label: Show info
                icon: material/information-outline
              - label: Hide info
                icon: material/information
            text: >-
              <p>Welcome Mat for <a href="https://www.openstreetmap.org" target="_blank">OpenStreetMap</a> community and <a href="https://osmfoundation.org" target="_blank">Foundation</a>. OpenStreetMap is the free and editable map of the world, created and maintained by a huge international community. Anybody can create an account and start editing on <a href="https://www.openstreetmap.org" target="_blank">OpenStreetMap</a> within minutes.</p>
              <p>These guides are licensed under <a href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">Creative Commons Attribution-ShareAlike 2.0 Generic License</a> if you would like to contribute or have any feedback on these, please feel free to raise an issue in this <a href="https://github.com/osmfoundation/welcome-mat/issues" target="_blank">repository</a>.</p>
          copyright: © 2019 – 2023 OpenStreetMap Foundation, <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/2.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">Creative Commons Attribution-ShareAlike 2.0 Generic License</a>. <a href="#__consent">Change cookie settings</a>
          theme:
            palette:
              - toggle:
                  name: Switch to dark mode
              - toggle:
                  name: Switch to light mode
          nav_translations:
            Home: Home
            # About: About us
            What is OpenStreetMap: What is OpenStreetMap?
            Who is OpenStreetMap: Who is OpenStreetMap?
            Why use OpenStreetMap: Why use OpenStreetMap?
            How can we give back: How can we give back?

            About Community: OpenStreetMap Community
            History of OSM: What is the history of OSM?
            OSMF: What is the OSM Foundation?
            Local Chapters: How are Local Chapters formed?
            Working Groups: Tell me about OSM Foundation Working Groups
            Consumers: Who uses OpenStreetMap?
            OSM News: What's new with OpenStreetMap?
            Donate: How can we give money to OpenStreetMap?
            Contact: How to get in touch

            Working with data: Working with OpenStreetMap Data
            Data quality: How good is OSM data?
            Contribute data: Organized Editing in OpenStreetMap
            Humanitarian campaign: We’re planning a humanitarian campaign using OSM, what do we need to know?
            Research with OSM: How can I research with OSM?
            Find a developer: Where do we find a good developer or company to build with OSM?
            Downloading and using: Downloading and using OSM data

        - locale: uk
          name: Українська
          site_name: Ласкаво просимо до OpenStreetMap
          announce: 
            toggle:
              - label: Показати інформацію
                icon: material/information-outline
              - label: Приховати інформацію
                icon: material/information
            text: >-
              <p>Вітаємо вас у цьому посібнику спільноти <a href="https://www.openstreetmap.org" target="_blank">OpenStreetMap</a> та <a href="https://osmfoundation.org" target="_blank">Фундації</a> проєкту. OpenStreetMap – це вільна мапа світу покращувати яку може кожен, яка створена та підтримується зусиллями величезної міжнародної спільноти. Будь-хто може зареєструватись в проєкті та розпочати вносити свої зміни в <a href="https://www.openstreetmap.org" target="_blank">OpenStreetMap</a> за лічені хвилини.</p>
              <p>Матеріали цього посібника розповсюджуються на умовах Ліцензії <a href="https://creativecommons.org/licenses/by-sa/2.0/deed.uk" target="_blank">Creative Commons Attribution-ShareAlike 2.0 Generic License</a> і якщо у вас є бажання взяти участь його вдосконалені, або у вас є побажання щодо його покращення, не соромтеся створити тікет у нашому <a href="https://github.com/osmfoundation/welcome-mat/issues" target="_blank">репозиторії</a>.</p>
          copyright: "© 2019 – 2023 Фундація OpenStreetMap, <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/2.0/deed.uk\" target=\"_blank\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/2.0/80x15.png\" /></a><br />Матеріали цього сайту ліцензуються на умовах Ліцензії – <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/2.0/deed.uk\" target=\"_blank\">Creative Commons Attribution-ShareAlike 2.0 Generic License</a>. <a href=\"#__consent\">Change cookie settings</a>"
          theme:
            palette:
              - toggle:
                  name: Увімкнути темну тему
              - toggle:
                  name: Увімкнути світлу тему
          nav_translations:
            Home: Головна
            # About: Про нас
            What is OpenStreetMap: Що таке OpenStreetMap?
            Who is OpenStreetMap: Хто є в OpenStreetMap?
            Why use OpenStreetMap: Чому OpenStreetMap?
            How can we give back: Внесок в OpenStreetMap

            About Community: Спільнота OpenStreetMap
            History of OSM: Історія OpenStreetMap
            OSMF: Що таке Фундація OSM?
            Local Chapters: Як створюються місцеві осередки?
            Working Groups: Розкажіть про робочі групи OSM Foundation
            Consumers: Хто користується даними OpenStreetMap?
            OSM News: Що нового в OpenStreetMap?
            Donate: Як ми можемо надати фінасову підтримку OpenStreetMap?
            Contact: Як зв'язатися?

            Working with data: Використання даних OpenStreetMap
            Data quality: Наскільки якісні дані OSM?
            Contribute data: Організоване редагування в OpenStreetMap
            Humanitarian campaign: Ми плануємо гуманітарну кампанію з використанням OSM, що нам потрібно знати?
            Research with OSM: Як я можу використовувати OSM в дослідженнях?
            Find a developer: Де знайти хорошого розробника чи компанію для створення продукту з використанням OSM?
            Downloading and using: Завантаження та використання даних OSM
